parameters:
  - name: packageName
    type: string
  - name: ddlFileName
    type: string

variables:
  - name: containerRegistryUrl
    value: exampleplatformacr.azurecr.io
  - name: containerRegistryServiceConnection
    value: exampleplatformacr
  - name: buildDate
    value: $[format('{0:yyyy}.{0:MM}.{0:dd}', pipeline.startTime)]
  - name: buildRevision
    value: $[counter(variables['buildDate'], 1)]
  - name: buildNumber
    value: $(buildDate).$(buildRevision)

stages:
  - stage: build_and_push
    displayName: Build & Push Docker image to registry
    jobs:
      - template: consumer/jobs/build.yml@platform
        parameters:
          containerRegistryUrl: $(containerRegistryUrl)
          containerRegistryServiceConnection: $(containerRegistryServiceConnection)
          packageName: ${{ parameters.packageName }}
          ddlFileName: ${{ parameters.ddlFileName }}
          buildNumber: $(buildNumber)

  - stage: deploy_to_aca
    displayName: Deploy to ACA
    dependsOn:
      - build_and_push
    jobs:
      - template: consumer/jobs/deploy-to-aca.yml@platform
        parameters:
          buildNumber: $(buildNumber)
