trigger:
  - main

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: lint_and_test
    displayName: Lint and test
    jobs:
      - job: lint
        displayName: Lint
        steps:
          - bash: ./platform/steps/shell_linting.sh $(pwd)/platform
            displayName: Lint platform Bash scripts

          - bash: ./platform/steps/shell_linting.sh $(pwd)/consumer
            displayName: Lint consumer Bash scripts

      - job: unit_test
        displayName: Unit test
        dependsOn: lint_and_test
        steps:
          - task: UsePythonVersion@0
            displayName: Use Python 3.9
            inputs:
              versionSpec: 3.9

          - bash: |
              python -m pip install --upgrade pip
              pip install pipenv
            displayName: Install pipenv

          - bash: pipenv install
            displayName: Install dependencies

          - bash: pipenv run pytest
            displayName: Run unit tests
