parameters:
  - name: packageName
    type: string
  - name: ddlFileName
    type: string

variables:
  - name: containerRegistryUrl
    value: exampleplatformacr.azurecr.io
  - name: containerRegistryServiceConnection
    value: exampleplatformacr

stages:
  - stage: build_and_push
    displayName: Build & Push Docker image to registry
    jobs:
      - template: consumer/jobs/build.yml@platform
        parameters:
          containerRegistryUrl: $(containerRegistryUrl)
          containerRegistryServiceConnection: $(containerRegistryServiceConnection)
          packageName: ${{ parameters.packageName }}
          ddlFileName: ${{ parameters.ddlFileName }}
