parameters:
  - name: unitTestProject
    type: string
  - name: integrationTestProject
    type: string
  - name: packageName
    type: string
  - name: ddlFileName
    type: string
  - name: workingDirectory
    type: string
    default: $(Build.SourcesDirectory)/$(buildRepositoryName)
  - name: deploymentRegions
    type: object
    default:
      - AU
      - US

variables:
  - name: containerRegistryUrl
    value: exampleplatformacr.azurecr.io
  - name: containerRegistryServiceConnection
    value: exampleplatformacr
  - name: buildDate
    value: $[format('{0:yyyy}.{0:MM}.{0:dd}', pipeline.startTime)]
  - name: buildRevision
    value: $[counter(variables['buildDate'], 1)]
  - name: buildNumber
    value: $(buildDate).$(buildRevision)
  - name: buildRepositoryName
    value: ${{ split(variables['Build.Repository.Name'], '/')[1] }}

stages:
  - template: consumer/stages/build-and-push.yml@platform
    parameters:
      containerRegistryUrl: $(containerRegistryUrl)
      containerRegistryServiceConnection: $(containerRegistryServiceConnection)
      unitTestProject: ${{ parameters.unitTestProject }}
      packageName: ${{ parameters.packageName }}
      ddlFileName: ${{ parameters.ddlFileName }}
      buildNumber: $(buildNumber)
      workingDirectory: ${{ parameters.workingDirectory }}

  - template: consumer/stages/dev.yml@platform
    parameters:
      containerRegistryUrl: $(containerRegistryUrl)
      containerRegistryServiceConnection: $(containerRegistryServiceConnection)
      integrationTestProject: ${{ parameters.integrationTestProject }}
      buildNumber: $(buildNumber)
      workingDirectory: ${{ parameters.workingDirectory }}

  - ${{ each region in parameters.deploymentRegions }}:
      - template: consumer/stages/prod.yml@platform
        parameters:
          containerRegistryUrl: $(containerRegistryUrl)
          buildNumber: $(buildNumber)
          workingDirectory: ${{ parameters.workingDirectory }}
          region: ${{ region }}
