parameters:
  - name: unitTestProject
    type: string
  - name: packageName
    type: string
  - name: ddlFileName
    type: string
  - name: workingDirectory
    type: string
    default: $(Build.SourcesDirectory)/$(buildRepositoryName)

variables:
  - name: containerRegistryUrl
    value: exampleplatformacr.azurecr.io
  - name: containerRegistryServiceConnection
    value: exampleplatformacr
  - name: buildDate
    value: $[format('{0:yyyy}.{0:MM}.{0:dd}', pipeline.startTime)]
  - name: buildRevision
    value: $[counter(variables['buildDate'], 1)]
  - name: buildNumber
    value: $(buildDate).$(buildRevision)
  - name: buildRepositoryName
    value: ${{ split(variables['Build.Repository.Name'], '/')[1] }}

stages:
  - stage: build_and_push
    displayName: Build & Push Docker image to registry
    jobs:
      - template: consumer/jobs/build.yml@platform
        parameters:
          containerRegistryUrl: $(containerRegistryUrl)
          containerRegistryServiceConnection: $(containerRegistryServiceConnection)
          unitTestProject: ${{ parameters.unitTestProject }}
          packageName: ${{ parameters.packageName }}
          ddlFileName: ${{ parameters.ddlFileName }}
          buildNumber: $(buildNumber)
          workingDirectory: ${{ parameters.workingDirectory }}

  - stage: deploy_to_aca
    displayName: Deploy to ACA
    dependsOn:
      - build_and_push
    jobs:
      - template: consumer/jobs/deploy-to-aca.yml@platform
        parameters:
          containerRegistryUrl: $(containerRegistryUrl)
          buildNumber: $(buildNumber)
