parameters:
  - name: containerRegistryUrl
    type: string
  - name: containerRegistryServiceConnection
    type: string
  - name: unitTestProject
    type: string
  - name: packageName
    type: string
  - name: ddlFileName
    type: string
  - name: buildNumber
    type: string
  - name: workingDirectory
    type: string

stages:
  - stage: build_and_push
    displayName: Build & Push Docker image to registry
    jobs:
      - template: ../jobs/build-and-push.yml@platform
        parameters:
          containerRegistryUrl: ${{ parameters.containerRegistryUrl }}
          containerRegistryServiceConnection: ${{ parameters.containerRegistryServiceConnection }}
          unitTestProject: ${{ parameters.unitTestProject }}
          packageName: ${{ parameters.packageName }}
          ddlFileName: ${{ parameters.ddlFileName }}
          buildNumber: ${{ parameters.buildNumber }}
          workingDirectory: ${{ parameters.workingDirectory }}
