stages:
  - stage: dev
    displayName: DEV
    dependsOn:
      - build_and_push
    jobs:
      - template: ../jobs/deploy-to-aca.yml@platform
        parameters:
          containerRegistryUrl: ${{ parameters.containerRegistryUrl }}
          buildNumber: ${{ parameters.buildNumber }}
          workingDirectory: ${{ parameters.workingDirectory }}
