stages:
  - stage: deploy_to_aca
    displayName: Deploy to ACA
    dependsOn:
      - build_and_push
    jobs:
      - template: consumer/jobs/deploy-to-aca.yml@platform
        parameters:
          containerRegistryUrl: ${{ parameters.containerRegistryUrl }}
          buildNumber: ${{ parameters.buildNumber }}
          workingDirectory: ${{ parameters.workingDirectory }}
