repository_name      = "$(buildRepositoryName)"
aca_environment_id   = "$(acaEnvironmentId)"
aca_user_identity_id = "$(acaUserIdentityId)"
acr_url              = "#{containerRegistryUrl}#"
build_number         = "#{buildNumber}#"
