parameters:
  - name: containerRegistryUrl
    type: string
  - name: buildNumber
    type: string
  - name: workingDirectory
    type: string

jobs:
  - deployment: deploy
    displayName: Deploy
    environment: exampleplatformaca
    variables:
      - group: exampleplatformacasg
      - name: terraformVersion
        value: '1.3.0'
      - name: azureSubscriptionServiceConnectionName
        value: example-platform-azure-kubernetes
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              persistCredentials: true

            - checkout: platform

            - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
              displayName: Install Terraform
              inputs:
                terraformVersion: $(terraformVersion)

            - bash: |
                cat ${{ parameters.workingDirectory }}/pipeline/aca/terraform.tfvars >> terraform.tfvars
              displayName: Combine consumer-provided and platform-provided terraform.tfvars files
              workingDirectory: $(Build.SourcesDirectory)/example-platform-dotnet-pipeline/consumer/terraform

            - task: qetza.replacetokens.replacetokens-task.replacetokens@3
              displayName: Insert pipeline variables into terraform.tfvars
              inputs:
                rootDirectory: $(Build.SourcesDirectory)/example-platform-dotnet-pipeline
                targetFiles: '**/consumer/terraform/terraform.tfvars'
                escapeType: none
                enableTransforms: true

            - task: TerraformCLI@0
              displayName: Terraform init
              inputs:
                command: init
                backendType: azurerm
                backendServiceArm: ${{ variables.azureSubscriptionServiceConnectionName }}
                backendAzureRmResourceGroupName: ${{ variables.resourceGroupName }}
                backendAzureRmStorageAccountName: ${{ variables.terraformStateStorageAccountName }}
                backendAzureRmContainerName: ${{ variables.terraformStateStorageAccountContainerName }}
                backendAzureRmKey: $(buildRepositoryName).tfstate
                workingDirectory: $(Build.SourcesDirectory)/example-platform-dotnet-pipeline/consumer/terraform

            - task: TerraformCLI@0
              displayName: Terraform validate
              inputs:
                command: validate
                backendType: azurerm
                environmentServiceName: ${{ variables.azureSubscriptionServiceConnectionName }}
                workingDirectory: $(Build.SourcesDirectory)/example-platform-dotnet-pipeline/consumer/terraform

            - task: TerraformCLI@0
              displayName: Terraform plan
              inputs:
                command: plan
                backendType: azurerm
                commandOptions: -out=tfplan -input=false
                environmentServiceName: ${{ variables.azureSubscriptionServiceConnectionName }}
                workingDirectory: $(Build.SourcesDirectory)/example-platform-dotnet-pipeline/consumer/terraform

            - task: TerraformCLI@0
              displayName: Terraform apply
              inputs:
                command: apply
                backendType: azurerm
                environmentServiceName: ${{ variables.azureSubscriptionServiceConnectionName }}
                workingDirectory: $(Build.SourcesDirectory)/example-platform-dotnet-pipeline/consumer/terraform

            - task: AzureCLI@2
              displayName: ACA Readiness check
              inputs:
                azureSubscription: ${{ variables.azureSubscriptionServiceConnectionName }}
                scriptType: bash
                scriptLocation: scriptPath
                scriptPath: $(Build.SourcesDirectory)/example-platform-dotnet-pipeline/consumer/steps/aca_readiness_check.sh
                arguments: '$(buildRepositoryName) $(resourceGroupName) $(buildNumber)'
