parameters:
  - name: dependsOn
    type: object
    default: []
  - name: variables
    type: object
    default: []
  - name: containerRegistryUrl
    type: string
  - name: containerRegistryServiceConnection
    type: string
  - name: integrationTestProject
    type: string
  - name: workingDirectory
    type: string

jobs:
  - job: integration_tests
    displayName: Integration tests
    dependsOn: ${{ parameters.dependsOn }}
    variables: ${{ parameters.variables }}
    steps:
      - checkout: self
        persistCredentials: true

      - checkout: platform

      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: ${{ parameters.containerRegistryServiceConnection }}

      - task: FileTransform@1
        displayName: Update integration test client base URL
        inputs:
          folderPath: ${{ parameters.workingDirectory }}
          targetFiles: '**/appsettings.json'
          fileType: json

      - bash: $(Build.SourcesDirectory)/example-platform-dotnet-pipeline/consumer/steps/run_integration_tests.sh ${{ parameters.containerRegistryUrl }} $(pwd) ${{ parameters.integrationTestProject }}
        workingDirectory: ${{ parameters.workingDirectory }}
        displayName: Run integration tests

      - task: PublishTestResults@2
        displayName: Publish integration test results
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: '**/*.trx'
          testRunTitle: Integration test
